version: 2
jobs:
  build:
    docker:
      - image: ghcr.io/h3poteto/pleroma:1.13.4-slim-buster
        environment:
          MIX_ENV: test
          DB_HOST: 127.0.0.1
          DB_USER: pleroma
          DB_PASSWORD: pleroma
          DB_NAME: pleroma_test
          ROLLBAR_ACCESS_TOKEN: dummy
      - image: postgres:13.2-alpine
        command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
        environment:
          POSTGRES_USER: pleroma
          POSTGRES_PASSWORD: pleroma
          POSTGRES_DB: pleroma_test
    working_directory: /var/opt/app
    steps:
      - checkout
      - restore_cache:
          name: Restoring cache - deps
          keys:
            - deps-1.13.4-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
            - deps-1.13.4-{{ checksum "mix.exs" }}-
      - restore_cache:
          name: Restoring cache - _build
          keys:
            - _build-1.13.4-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
            - _build-1.13.4-{{ checksum "mix.exs" }}
      - restore_cache:
          name: Restoring cache - home
          keys:
            - home-1.13.4-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
            - home-1.13.4-{{ checksum "mix.exs" }}
      - run:
          name: Mix packages install
          command: |
            mix local.hex --force
            mix deps.get
      - save_cache:
          name: Saving cache - deps
          key: deps-1.13.4-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
          paths:
            - "deps"
      - run:
          name: Compile deps packages
          command: |
            mix local.rebar --force
            mix deps.compile
      - save_cache:
          name: Saving cache - _build
          key: _build-1.13.4-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
          paths:
            - "_build"
      - save_cache:
          name: Saving cache - home
          key: home-1.13.4-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
          paths:
            - "~/.cache"
            - "~/.mix"
            - "~/.hex"
      - run:
          name: Migration database
          command: |
            mix ecto.create
            mix ecto.migrate
      - run:
          name: test
          command: |
            mix coveralls --preload-modules

  image:
    machine: true
    steps:
      - checkout
      - run:
          name: phoenix docker build
          command: |
            docker build -t $AWS_ECR_REPOSITORY:$CIRCLE_SHA1 -f dockerfiles/phoenix/Dockerfile .
            docker tag $AWS_ECR_REPOSITORY:$CIRCLE_SHA1 $AWS_ECR_REPOSITORY:latest
      - run:
          name: phoenix docker push
          command: |
            aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin https://564677439943.dkr.ecr.ap-northeast-1.amazonaws.com
            docker push $AWS_ECR_REPOSITORY:$CIRCLE_SHA1
            docker push $AWS_ECR_REPOSITORY:latest
      - run:
          name: nginx docker build
          command: |
            cd dockerfiles/nginx
            docker build -t $NGINX_ECR:$CIRCLE_SHA1 .
            docker build -t $NGINX_ECR:latest .
      - run:
          name: nginx docker push
          command: |
            aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin https://564677439943.dkr.ecr.ap-northeast-1.amazonaws.com
            docker push $NGINX_ECR:$CIRCLE_SHA1
            docker push $NGINX_ECR:latest

  create_pull_request:
    docker:
      - image: circleci/golang:1.15-buster
    steps:
      - run:
          name: Install_hub
          command: |
            curl -sSLf https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz | \
            tar zxf - --strip-components=1 -C /tmp/ && \
            sudo mv /tmp/bin/hub /usr/local/bin/hub
            hub --version
      - run:
          name: Update_tag_and_create_pr
          command: |
            git config --global user.name ${GITHUB_NAME}
            git config --global user.email ${GITHUB_EMAIL}
            git clone https://${GITHUB_NAME}:${GITHUB_TOKEN}@github.com/h3poteto/k8s-services.git
            cd k8s-services
            git init
            git checkout -b update-pleromaio-image-${CIRCLE_SHA1}
            sed -i -e "s/\(564677439943\.dkr\.ecr\.ap-northeast-1\.amazonaws\.com\/h3poteto\/pleroma\/phoenix:\)[0-9a-z]\+.*$/\1$CIRCLE_SHA1/g" external-prd/pleromaio/deployment.yml
            sed -i -e "s/\(564677439943\.dkr\.ecr\.ap-northeast-1\.amazonaws\.com\/h3poteto\/pleroma\/nginx:\)[0-9a-z]\+.*$/\1$CIRCLE_SHA1/g" external-prd/pleromaio/deployment.yml
            git add .
            git commit -m "Update docker image for pleromaio to ${CIRCLE_SHA1}"
            git push --set-upstream origin update-pleromaio-image-${CIRCLE_SHA1}
            hub pull-request -m "[Image update] pleromaio ${CIRCLE_SHA1}"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - image:
          filters:
            branches:
              only:
                - master
      - create_pull_request:
          filters:
            branches:
              only:
                - master
          requires:
            - image
