name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test
      DB_HOST: 127.0.0.1
      DB_USER: pleroma
      DB_PASSWORD: pleroma
      DB_NAME: pleroma_test

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: pleroma
          POSTGRES_PASSWORD: pleroma
          POSTGRES_DB: pleroma_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.13.4' # Define the elixir version [required]
        otp-version: '24.1' # Define the OTP version [required]
    - name: Install packages
      run: |
        sudo apt-get install -y libimage-exiftool-perl ffmpeg
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: |
        mix local.hex --force
        mix deps.get
        mix local.rebar --force
        mix deps.compile
    - name: Migrate database
      run: |
        mix ecto.create
        mix ecto.migrate

    - name: Run tests
      run: mix coveralls --preload-modules
