name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/h3poteto/pleroma:1.14.5-otp24-slim
      options: --user root
      env:
        MIX_ENV: test
        DB_HOST: postgres
        DB_USER: pleroma
        DB_PASSWORD: pleroma
        DB_NAME: pleroma_test
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: pleroma
          POSTGRES_PASSWORD: pleroma
          POSTGRES_DB: pleroma_test
          POSTGRESQL_FSYNC: "off"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        mix local.hex --force
        mix deps.get
        mix local.rebar --force
        mix deps.compile
    - name: Migrate database
      run: |
        ls -lha config
        mix ecto.create
        mix ecto.migrate
    - name: Run tests
      run: mix test --cover --preload-modules
